include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    flutter_style_todos: true
    library_private_types_in_public_api: false
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_late: true
    use_build_context_synchronously: false
