name: Build test

on: [push, pull_request]

jobs:
  test_iOS:
    name: Test iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib
      - run: cd example; flutter build ios --no-codesign

  test_android:
    name: Test android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: '8.x'
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib
      - run: sudo echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;20.0.5594570"
      - run: cd example; flutter build apk --debug
