name: "Issue Labeler"

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Auto label
      uses: Renato66/auto-label@5b5a5586770b1200629b78e82a2ceb505756675b # v2.1.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        ignore-comments: true
        default-labels: '["await triage"]'
